name: deploy-book

on:
  push:
    branches:
      - main

# Only one Pages deployment at a time; don’t cancel the one in‐flight
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Build the book and publish the HTML as an artifact
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clean & Build Jupyter Book
        run: |
          jupyter-book clean glocal-scraping-guideline
          jupyter-book build glocal-scraping-guideline

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # point at the folder that contains your built HTML
          path: glocal-scraping-guideline/_build/html

  # Download the artifact and deploy it to GitHub Pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write        # allow writing to the Pages deployment
      id-token: write     # required by the deploy-pages action
    steps:
      - name: Download pages artifact
        uses: actions/download-pages-artifact@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
